<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.3" />
    <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="4.14.0" />
    <PackageVersion Include="Scriban" Version="5.12.0" />
    <PackageVersion Include="TimeWarp.Amuru" Version="1.0.0-beta.34" />
    <PackageVersion Include="TimeWarp.Build.Tasks" Version="1.0.0" />
    <PackageVersion Include="TimeWarp.Nuru" Version="3.0.0-beta.71" />
    <PackageVersion Include="TimeWarp.Nuru.DevCli" Version="3.0.0-beta.71" />
  </ItemGroup>
</Project>
