name: Publish to NuGet

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allow manual kick off
    inputs:
      force_publish:
        description: 'Force publish to NuGet'
        type: boolean
        default: false
        required: false
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday (UTC time)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Process Release
      shell: pwsh
      run: |
        ./.github/scripts/process-release.ps1 `
          -WorkspacePath $env:GITHUB_WORKSPACE `
          -RepoToken ${{ secrets.REPO_ACCESS_TOKEN }} `
          -NugetKey ${{ secrets.PUBLISH_TO_NUGET_ORG }} `
          -ForcePublish ${{ inputs.force_publish || false }}
