name: Test Publish Workflow

on:
  workflow_dispatch: # Only manual trigger for testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Compare release versions
      id: get-releases
      shell: pwsh
      run: |
        ./.github/scripts/compare-versions.ps1

    - name: Show version comparison results
      shell: pwsh
      run: |
        Write-Host "Simple Icons Version: ${{ steps.get-releases.outputs.si }}"
        Write-Host "Library Version: ${{ steps.get-releases.outputs.lib }}"

    - name: Test project update (without committing)
      shell: pwsh
      run: |
        # Create backup of files
        Copy-Item source/timewarp-simple-icons/timewarp-simple-icons.csproj source/timewarp-simple-icons/timewarp-simple-icons.csproj.bak
        Copy-Item releases.md releases.md.bak
        
        # Run update script
        ./.github/scripts/update-project.ps1 -NewVersion '${{ steps.get-releases.outputs.si }}'
        
        # Show changes that would be made
        Write-Host "`nChanges that would be made to csproj:"
        git diff source/timewarp-simple-icons/timewarp-simple-icons.csproj
        
        Write-Host "`nChanges that would be made to releases.md:"
        git diff releases.md
        
        # Restore original files
        Move-Item -Force source/timewarp-simple-icons/timewarp-simple-icons.csproj.bak source/timewarp-simple-icons/timewarp-simple-icons.csproj
        Move-Item -Force releases.md.bak releases.md

    - name: Test icon update (without committing)
      shell: pwsh
      run: |
        # Backup icons directory
        if (Test-Path source/timewarp-simple-icons/icons) {
          Copy-Item source/timewarp-simple-icons/icons source/timewarp-simple-icons/icons.bak -Recurse
        }
        
        # Run update script
        ./.github/scripts/update-icons.ps1 -WorkspacePath '${{ github.workspace }}'
        
        # Show changes that would be made
        Write-Host "`nIcon files that would be updated:"
        git status source/timewarp-simple-icons/icons
        
        # Restore original icons
        Remove-Item source/timewarp-simple-icons/icons -Recurse -Force -ErrorAction SilentlyContinue
        if (Test-Path source/timewarp-simple-icons/icons.bak) {
          Move-Item source/timewarp-simple-icons/icons.bak source/timewarp-simple-icons/icons
        }

    - name: Test git commands (without pushing)
      shell: pwsh
      run: |
        Write-Host "Git commands that would be executed:"
        Write-Host "git config --local user.email 'github-actions-bot@timewarp.enterprises'"
        Write-Host "git config --local user.name 'GitHub Actions Bot'"
        Write-Host "git add ."
        Write-Host "git commit -m 'Update to simple-icons version ${{ steps.get-releases.outputs.si }}'"
        Write-Host "git push"
